export type RootStackParamList = {
  SplashScreen: undefined;
  Onboarding: { screen: keyof OnboardingStackParamList };
  Auth: { screen: keyof AuthStackParamList };
  Social: { screen: keyof SocialStackParamList };
  Profile: { screen: keyof ProfileStackParamList };
  Finance: { screen: keyof FinanceStackParamList };
  ECommerce: { screen: keyof ECommerceStackParamList };
  Reading: { screen: keyof ReadingStackParamList };
  Fitness: { screen: keyof FitnessStackParamList };
  Health: { screen: keyof HealthStackParamList };
  Crypto: { screen: keyof CryptoStackParamList };
  FoodDelivery: { screen: keyof FoodDeliveryStackParamList };
  Menu: { screen: keyof MenuStackParamList };
  BeStrong: { screen: keyof BeStrongStackParamList };
  PricePlan: { screen: keyof PricePlanStackParamList };
};
export type OnboardingStackParamList = {
  OnboardingIntro: undefined;
  Onboarding01: undefined;
  Onboarding02: undefined;
  Onboarding03: undefined;
  Onboarding04: undefined;
  Onboarding05: undefined;
  Onboarding06: undefined;
  Onboarding07: undefined;
  Onboarding08: undefined;
  Onboarding09: undefined;
  Onboarding10: undefined;
};
export type AuthStackParamList = {
  AuthIntro: undefined;
  SignIn: undefined;
  SignUp: undefined;
  CreateAccount: undefined;
  ForgotPassword: undefined;
  Verify: undefined;
  Authenticate: undefined;
};

export type ProfileStackParamList = {
  ProfileIntro: undefined;
  Profile01: undefined;
  Profile02: undefined;
  Profile03: undefined;
  Profile04: undefined;
  Profile05: undefined;
  Profile06: undefined;
  Profile07: undefined;
  Profile08: undefined;
  Profile09: undefined;
  Profile10: undefined;
};
export type SocialStackParamList = {
  SocialIntro: undefined;
  Social01: undefined;
  Social02: undefined;
  Social03: undefined;
  Social04: undefined;
  Social05: undefined;
  Social06: undefined;
  Social07: undefined;
  Social08: undefined;
  Social09: undefined;
  Social10: undefined;
};
export type FinanceStackParamList = {
  FinanceIntro: undefined;
  Finance01: undefined;
  Finance02: undefined;
  Finance03: undefined;
  Finance04: undefined;
  Finance05: undefined;
  Finance06: undefined;
  Finance07: undefined;
  Finance08: undefined;
  Finance09: undefined;
  Finance10: undefined;
  Finance11: undefined;
  Finance12: undefined;
  Finance13: undefined;
};
export type ReadingStackParamList = {
  ReadingIntro: undefined;
  Reading01: undefined;
  Reading02: undefined;
  Reading03: undefined;
  Reading04: undefined;
  Reading05: undefined;
  Reading06: undefined;
  Reading07: undefined;
  Reading08: undefined;
  Reading09: undefined;
  Reading10: undefined;
};
export type ECommerceStackParamList = {
  ECommerceIntro: undefined;
  ECommerce01: undefined;
  ECommerce02: undefined;
  ECommerce03: undefined;
  ECommerce04: undefined;
  ECommerce05: undefined;
  ECommerce06: undefined;
  ECommerce07: undefined;
  ECommerce08: undefined;
  ECommerce09: undefined;
  ECommerce10: undefined;
};
export type FitnessStackParamList = {
  FitnessIntro: undefined;
  Fitness01: undefined;
  Fitness02: undefined;
  Fitness03: undefined;
  Fitness04: undefined;
  Fitness05: undefined;
  Fitness06: undefined;
  Fitness07: undefined;
  Fitness08: undefined;
  Fitness09: undefined;
  Fitness10: undefined;
};
export type HealthStackParamList = {
  HealthIntro: undefined;
  Health01: undefined;
  Health02: undefined;
  Health03: undefined;
  Health04: undefined;
  Health05: undefined;
  Health06: undefined;
  Health07: undefined;
  Health08: undefined;
  Health09: undefined;
  Health10: undefined;
};
export type CryptoStackParamList = {
  CryptoIntro: undefined;
  Crypto01: undefined;
  Crypto02: undefined;
  Home: undefined;
  DepositTrhoughPlatform: undefined;
  SellBxg: undefined;
  Wallet: undefined;
  Transfer: undefined;
  Crypto08: undefined;
  Crypto09: undefined;
  Crypto10: undefined;
};
export type FoodDeliveryStackParamList = {
  FoodDeliveryIntro: undefined;
  FoodDelivery01: undefined;
  FoodDelivery02: undefined;
  FoodDelivery03: undefined;
  FoodDelivery04: undefined;
  FoodDelivery05: undefined;
  FoodDelivery06: undefined;
  FoodDelivery07: undefined;
  FoodDelivery08: undefined;
  FoodDelivery09: undefined;
  FoodDelivery10: undefined;
};
export type MenuStackParamList = {
  Home: undefined;
  Menu01: undefined;
  Menu02: undefined;
  Menu03: undefined;
  Menu04: undefined;
  Menu05: undefined;
  Menu06: undefined;
  Menu07: undefined;
  Menu08: undefined;
  Menu09: undefined;
  Menu10: undefined;
};
export type PricePlanStackParamList = {
  PricePlanIntro: undefined;
  PricePlan01: undefined;
  PricePlan02: undefined;
  PricePlan03: undefined;
  PricePlan04: undefined;
  PricePlan05: undefined;
  PricePlan06: undefined;
  PricePlan07: undefined;
  PricePlan08: undefined;
  PricePlan09: undefined;
  PricePlan10: undefined;
};
export type BeStrongStackParamList = {
  Onboarding: undefined;
  SignIn: undefined;
  Menu: undefined;
  Categories: undefined;
  QuotesDetails: undefined;
  Categories1: undefined;
  HomePage: undefined;
  Quotes_Details: undefined;
  Categories2: undefined;
  Categories3: undefined;
  Success: undefined;
  Author: undefined;
  UpgradePremium: undefined;
};
